on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -v -y
          sudo ln -s $HOME/.elan/bin/* /usr/local/bin;

      - name: Install python Lean dependencies
        run: python -m pip install --upgrade pip requests markdown2 toml mathlibtools toposort invoke

        #      - name: Link and fetch mathlib
        #        run: |
        #          leanproject get jjgarzella/adjunction_formula
        #          ln -s adjunction_formula project
        #          ( cd project && leanproject get-m )
        #          inv decls

      - name: Install Leanblueprint and generate web in tex env
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk update
            apk add --update make py3-pip git
            git config --global --add safe.directory `pwd`/adjunction_formula
            python3 -m pip install --upgrade pip requests wheel
            apk add pkgconfig graphviz graphviz-dev gcc musl-dev && \
            python3 -m pip install pygraphviz --global-option=build_ext --global-option="-L/usr/lib/graphviz/" --global-option="-R/usr/lib/graphviz/"
            #python3 -m pip install invoke git+https://github.com/plastex/plastex.git git+https://github.com/PatrickMassot/leanblueprint.git
            python3 -m pip install invoke git+https://github.com/plastex/plastex.git git+https://github.com/mpenciak/noleanblueprint.git
            inv qweb
            #inv qpdf
            #cp print/blueprint.pdf web/

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.github_token }}
          publish_dir: ./web
